### ISSUE TITLE
Ohio 2023 joint 81k wages one dep

### ISSUE THREAD

**Issue by feenberg** [PolicyEngine/policyengine-taxsim#85] opened 2024-11-05 13:48 UTC
Ohio 2023 joint 81k wages one dep

http://taxsim.nber.org/out2psl/test37

Again no report of taxable income or exemptions from the emulator, but I can guess that the emulator has 2 exemptions while TaxAct has 3.

**Comment by MaxGhenis** [comment] 2024-11-05 16:29
Likely duplicate of https://github.com/PolicyEngine/policyengine-taxsim/issues/53

**Closed** 2024-11-05 16:28 UTC
